schema: "classroom50/repo-config/v1"
classroom: "indprog"
assignment: "02-conveyor-belt"
owner:
  username: "GustavMadsen"
  id: 49937941
  accepted_at: "2026-09-07T12:40:50Z"
source:
  owner: "indprog"
  owner_id: 316953525
  repo: "python-template"
  branch: "main"
